NAME        := standard
VERSION     := 0.1.0
DESCRIPTION := Standard library to comunication with the operation system.
DEPEDENCIES := 
SOURCES     := standard.c

CFLAGS      += 
LDFLAGS     += -pthread

include ../Makefile.lib.inc
