NAME        := foundation
VERSION     := 0.1.0
DESCRIPTION := Basic and independent data structures used by the actor layer.
DEPEDENCIES := standard
SOURCES     := queue.c debug.c

CFLAGS      += 
LDFLAGS     += 

include ../Makefile.lib.inc

