NAME        := demo
VERSION     := 0.1.0
DESCRIPTION := Demonstration of actor system.
DEPEDENCIES := actors
SOURCES     := $(wildcard *.c)

CFLAGS      += 
LDFLAGS     += 

include ../Makefile.exec.inc
